/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import entity.*;
import java.util.Optional;
import java.time.LocalDate;
import java.time.LocalTime;


/**
 *
 * @author Gokhan
 */
public class Main extends javax.swing.JFrame {
    private static DAO passengerDAO, scheduleDAO, ticketDAO, trainDAO;

    public Main() {
        initComponents();
        refreshPassengersTable();
        refreshTicketsTable();
        refreshSchedulesTable();
        
        refreshTrainsTable();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelItemName2 = new javax.swing.JLabel();
        jTabbedPaneTrainSystem = new javax.swing.JTabbedPane();
        jPanelPassenger = new javax.swing.JPanel();
        jScrollPanePassenger = new javax.swing.JScrollPane();
        jTablePassenger = new javax.swing.JTable();
        jTextFieldPassengerID = new javax.swing.JTextField();
        jTextFieldPassengerFirstName = new javax.swing.JTextField();
        jTextFieldPassengerLastName = new javax.swing.JTextField();
        jTextFieldPassengerEmail = new javax.swing.JTextField();
        jLabelPassengerEmail = new javax.swing.JLabel();
        jLabelPassengerLastName = new javax.swing.JLabel();
        jLabelPassengerFirstName = new javax.swing.JLabel();
        jLabelPassengerID = new javax.swing.JLabel();
        jButtonInsertPassenger = new javax.swing.JButton();
        jButtonUpdatePassenger = new javax.swing.JButton();
        jButtonDeletePassenger = new javax.swing.JButton();
        jPanelTrain = new javax.swing.JPanel();
        jLabelTrainType = new javax.swing.JLabel();
        jLabelTrainID = new javax.swing.JLabel();
        jLabelMaxSpeed = new javax.swing.JLabel();
        jLabelTrainName = new javax.swing.JLabel();
        jTextFieldTrainType = new javax.swing.JTextField();
        jTextFieldTrainID = new javax.swing.JTextField();
        jTextFieldMaxSpeed = new javax.swing.JTextField();
        jTextFieldTrainName = new javax.swing.JTextField();
        jScrollPaneTrain = new javax.swing.JScrollPane();
        jTableTrain = new javax.swing.JTable();
        jButtonInsertTrain = new javax.swing.JButton();
        jButtonUpdateTrain = new javax.swing.JButton();
        jButtonDeleteTrain = new javax.swing.JButton();
        jPanelSchedule = new javax.swing.JPanel();
        jScrollPaneOrder = new javax.swing.JScrollPane();
        jTableSchedule = new javax.swing.JTable();
        jTextFieldScheduleID = new javax.swing.JTextField();
        jLabelScheduleID = new javax.swing.JLabel();
        jButtonInsertSchedule = new javax.swing.JButton();
        jButtonUpdateSchedule = new javax.swing.JButton();
        jButtonDeleteSchedule = new javax.swing.JButton();
        jLabelEndDateTime = new javax.swing.JLabel();
        jTextFieldEndDateTime = new javax.swing.JTextField();
        jLabelStartDateTime = new javax.swing.JLabel();
        jLabelTrainID1 = new javax.swing.JLabel();
        jLabelStartLocation = new javax.swing.JLabel();
        jTextFieldStartLocation = new javax.swing.JTextField();
        jTextFieldDestination = new javax.swing.JTextField();
        jTextFieldStartDateTime = new javax.swing.JTextField();
        jLabelDestination = new javax.swing.JLabel();
        jTextFieldTrainID1 = new javax.swing.JTextField();
        jPanelTicket = new javax.swing.JPanel();
        jLabelPassengerID1 = new javax.swing.JLabel();
        jLabelTicketID = new javax.swing.JLabel();
        jLabelPurchaseDateTime = new javax.swing.JLabel();
        jLabelScheduleID1 = new javax.swing.JLabel();
        jTextFieldPassengerID1 = new javax.swing.JTextField();
        jTextFieldPurchaseDateTime = new javax.swing.JTextField();
        jTextFieldTicketID = new javax.swing.JTextField();
        jTextFieldTicketCost = new javax.swing.JTextField();
        jButtonUpdateTicket = new javax.swing.JButton();
        jButtonDeleteTicket = new javax.swing.JButton();
        jButtonInsertTicket = new javax.swing.JButton();
        jScrollPaneTicket = new javax.swing.JScrollPane();
        jTableTicket = new javax.swing.JTable();
        jLabelTicketCost = new javax.swing.JLabel();
        jTextFieldScheduleID1 = new javax.swing.JTextField();

        jLabelItemName2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelItemName2.setText("Start Date Time");
        jLabelItemName2.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HotDog Stand CRUD");
        setResizable(false);

        jTabbedPaneTrainSystem.setName("Customer"); // NOI18N

        jTablePassenger.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PassengerID", "First Name", "Last Name", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePassenger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePassengerMouseClicked(evt);
            }
        });
        jScrollPanePassenger.setViewportView(jTablePassenger);

        jTextFieldPassengerEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPassengerEmailActionPerformed(evt);
            }
        });

        jLabelPassengerEmail.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelPassengerEmail.setText("Passenger Email");
        jLabelPassengerEmail.setToolTipText("");

        jLabelPassengerLastName.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelPassengerLastName.setText("Passenger Last Name");
        jLabelPassengerLastName.setToolTipText("");

        jLabelPassengerFirstName.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelPassengerFirstName.setText("Passenger First Name");

        jLabelPassengerID.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelPassengerID.setText("Passenger ID");

        jButtonInsertPassenger.setText("Insert");
        jButtonInsertPassenger.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonInsertPassenger.setIconTextGap(0);
        jButtonInsertPassenger.setInheritsPopupMenu(true);
        jButtonInsertPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertPassengerActionPerformed(evt);
            }
        });

        jButtonUpdatePassenger.setText("Update");
        jButtonUpdatePassenger.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonUpdatePassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdatePassengerActionPerformed(evt);
            }
        });

        jButtonDeletePassenger.setText("Delete");
        jButtonDeletePassenger.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDeletePassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletePassengerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPassengerLayout = new javax.swing.GroupLayout(jPanelPassenger);
        jPanelPassenger.setLayout(jPanelPassengerLayout);
        jPanelPassengerLayout.setHorizontalGroup(
            jPanelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPassengerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPassengerLayout.createSequentialGroup()
                        .addComponent(jButtonInsertPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButtonUpdatePassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(jButtonDeletePassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelPassengerLayout.createSequentialGroup()
                        .addGroup(jPanelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPassengerLayout.createSequentialGroup()
                                .addGroup(jPanelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPassengerLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelPassengerEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPassengerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPassengerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54))
                            .addGroup(jPanelPassengerLayout.createSequentialGroup()
                                .addGroup(jPanelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelPassengerLayout.createSequentialGroup()
                                        .addComponent(jLabelPassengerID, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(87, 87, 87))
                                    .addGroup(jPanelPassengerLayout.createSequentialGroup()
                                        .addComponent(jLabelPassengerFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPassengerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPassengerID, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPanePassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(318, 318, 318))))
        );
        jPanelPassengerLayout.setVerticalGroup(
            jPanelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPassengerLayout.createSequentialGroup()
                .addGroup(jPanelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPassengerLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPassengerID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPassengerID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPassengerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPassengerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPassengerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPassengerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPassengerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPassengerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPassengerLayout.createSequentialGroup()
                        .addContainerGap(31, Short.MAX_VALUE)
                        .addComponent(jScrollPanePassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanelPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsertPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdatePassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeletePassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        jLabelPassengerLastName.getAccessibleContext().setAccessibleName("ID");

        jTabbedPaneTrainSystem.addTab("Passenger", jPanelPassenger);

        jLabelTrainType.setText("Train Type");

        jLabelTrainID.setText("Train ID");

        jLabelMaxSpeed.setText("Max Speed");

        jLabelTrainName.setText("Train Name");

        jTableTrain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Train ID", "Train Type", "Train Name", "Max Speed"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTrain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTrainMouseClicked(evt);
            }
        });
        jScrollPaneTrain.setViewportView(jTableTrain);

        jButtonInsertTrain.setText("Insert");
        jButtonInsertTrain.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonInsertTrain.setIconTextGap(0);
        jButtonInsertTrain.setInheritsPopupMenu(true);
        jButtonInsertTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertTrainActionPerformed(evt);
            }
        });

        jButtonUpdateTrain.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonUpdateTrain.setIconTextGap(0);
        jButtonUpdateTrain.setInheritsPopupMenu(true);
        jButtonUpdateTrain.setLabel("Update");
        jButtonUpdateTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateTrainActionPerformed(evt);
            }
        });

        jButtonDeleteTrain.setActionCommand("Delete");
        jButtonDeleteTrain.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDeleteTrain.setIconTextGap(0);
        jButtonDeleteTrain.setInheritsPopupMenu(true);
        jButtonDeleteTrain.setLabel("Delete");
        jButtonDeleteTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteTrainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTrainLayout = new javax.swing.GroupLayout(jPanelTrain);
        jPanelTrain.setLayout(jPanelTrainLayout);
        jPanelTrainLayout.setHorizontalGroup(
            jPanelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrainLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTrainLayout.createSequentialGroup()
                        .addComponent(jButtonInsertTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdateTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButtonDeleteTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTrainLayout.createSequentialGroup()
                        .addGroup(jPanelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTrainLayout.createSequentialGroup()
                                .addComponent(jLabelMaxSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMaxSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelTrainLayout.createSequentialGroup()
                                .addComponent(jLabelTrainID, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTrainID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelTrainLayout.createSequentialGroup()
                                .addComponent(jLabelTrainType, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTrainType, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelTrainLayout.createSequentialGroup()
                                .addComponent(jLabelTrainName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTrainName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPaneTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(494, Short.MAX_VALUE))
        );
        jPanelTrainLayout.setVerticalGroup(
            jPanelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrainLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelTrainLayout.createSequentialGroup()
                        .addGroup(jPanelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTrainID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTrainID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTrainType, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTrainType, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTrainName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTrainName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMaxSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMaxSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPaneTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsertTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdateTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jTabbedPaneTrainSystem.addTab("Train", jPanelTrain);

        jTableSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Schedule ID", "Start Date Time", "End Date Time", "Destination", "Train ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableScheduleMouseClicked(evt);
            }
        });
        jScrollPaneOrder.setViewportView(jTableSchedule);

        jLabelScheduleID.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelScheduleID.setText("Schedule ID");

        jButtonInsertSchedule.setText("Insert");
        jButtonInsertSchedule.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonInsertSchedule.setIconTextGap(0);
        jButtonInsertSchedule.setInheritsPopupMenu(true);
        jButtonInsertSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertScheduleActionPerformed(evt);
            }
        });

        jButtonUpdateSchedule.setText("Update");
        jButtonUpdateSchedule.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonUpdateSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateScheduleActionPerformed(evt);
            }
        });

        jButtonDeleteSchedule.setText("Delete");
        jButtonDeleteSchedule.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDeleteSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteScheduleActionPerformed(evt);
            }
        });

        jLabelEndDateTime.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelEndDateTime.setText("End Date Time");
        jLabelEndDateTime.setToolTipText("");

        jLabelStartDateTime.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelStartDateTime.setText("Start Date Time");
        jLabelStartDateTime.setToolTipText("");

        jLabelTrainID1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelTrainID1.setText("Train ID");
        jLabelTrainID1.setToolTipText("");

        jLabelStartLocation.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelStartLocation.setText("Start Location");
        jLabelStartLocation.setToolTipText("");

        jTextFieldDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDestinationActionPerformed(evt);
            }
        });

        jLabelDestination.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelDestination.setText("Destination");
        jLabelDestination.setToolTipText("");

        javax.swing.GroupLayout jPanelScheduleLayout = new javax.swing.GroupLayout(jPanelSchedule);
        jPanelSchedule.setLayout(jPanelScheduleLayout);
        jPanelScheduleLayout.setHorizontalGroup(
            jPanelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelScheduleLayout.createSequentialGroup()
                        .addGroup(jPanelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelScheduleLayout.createSequentialGroup()
                                .addComponent(jLabelScheduleID, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldScheduleID)
                                .addGap(66, 66, 66))
                            .addGroup(jPanelScheduleLayout.createSequentialGroup()
                                .addGroup(jPanelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelScheduleLayout.createSequentialGroup()
                                        .addGroup(jPanelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelTrainID1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelEndDateTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelStartDateTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(30, 30, 30))
                                    .addGroup(jPanelScheduleLayout.createSequentialGroup()
                                        .addComponent(jLabelStartLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanelScheduleLayout.createSequentialGroup()
                                        .addComponent(jLabelDestination, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelScheduleLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jTextFieldDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelScheduleLayout.createSequentialGroup()
                                        .addGroup(jPanelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jTextFieldStartDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextFieldStartLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextFieldEndDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jTextFieldTrainID1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPaneOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(556, 556, 556))
                    .addGroup(jPanelScheduleLayout.createSequentialGroup()
                        .addComponent(jButtonInsertSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdateSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeleteSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelScheduleLayout.setVerticalGroup(
            jPanelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelScheduleLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelScheduleLayout.createSequentialGroup()
                        .addComponent(jScrollPaneOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelScheduleLayout.createSequentialGroup()
                        .addGroup(jPanelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldScheduleID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelScheduleLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabelScheduleID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelStartDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldStartDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelScheduleLayout.createSequentialGroup()
                                .addGroup(jPanelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelEndDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEndDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addGroup(jPanelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelStartLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldStartLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35))
                            .addGroup(jPanelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTrainID1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTrainID1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonInsertSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonUpdateSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDeleteSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))))
        );

        jTabbedPaneTrainSystem.addTab("Schedule", jPanelSchedule);

        jLabelPassengerID1.setText("Passenger ID");

        jLabelTicketID.setText("Ticket ID");

        jLabelPurchaseDateTime.setText("Purchase Date Time");

        jLabelScheduleID1.setText("Schedule ID");

        jButtonUpdateTicket.setText("Update");
        jButtonUpdateTicket.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonUpdateTicket.setIconTextGap(0);
        jButtonUpdateTicket.setInheritsPopupMenu(true);
        jButtonUpdateTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateTicketActionPerformed(evt);
            }
        });

        jButtonDeleteTicket.setText("Delete");
        jButtonDeleteTicket.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDeleteTicket.setIconTextGap(0);
        jButtonDeleteTicket.setInheritsPopupMenu(true);
        jButtonDeleteTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteTicketActionPerformed(evt);
            }
        });

        jButtonInsertTicket.setText("Insert");
        jButtonInsertTicket.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonInsertTicket.setIconTextGap(0);
        jButtonInsertTicket.setInheritsPopupMenu(true);
        jButtonInsertTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertTicketActionPerformed(evt);
            }
        });

        jTableTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket ID", "Passenger ID", "Purchase Date Time", "Ticket Cost", "Schedule ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTicketMouseClicked(evt);
            }
        });
        jScrollPaneTicket.setViewportView(jTableTicket);

        jLabelTicketCost.setText("Ticket Cost");

        javax.swing.GroupLayout jPanelTicketLayout = new javax.swing.GroupLayout(jPanelTicket);
        jPanelTicket.setLayout(jPanelTicketLayout);
        jPanelTicketLayout.setHorizontalGroup(
            jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTicketLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTicketLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButtonInsertTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdateTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeleteTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTicketLayout.createSequentialGroup()
                        .addGroup(jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTicketLayout.createSequentialGroup()
                                .addComponent(jLabelPurchaseDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPurchaseDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelTicketLayout.createSequentialGroup()
                                .addComponent(jLabelTicketID, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTicketID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelTicketLayout.createSequentialGroup()
                                .addComponent(jLabelPassengerID1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPassengerID1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelTicketLayout.createSequentialGroup()
                                .addComponent(jLabelScheduleID1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldScheduleID1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelTicketLayout.createSequentialGroup()
                                .addComponent(jLabelTicketCost, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTicketCost, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPaneTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanelTicketLayout.setVerticalGroup(
            jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTicketLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTicketLayout.createSequentialGroup()
                        .addGroup(jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTicketID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTicketID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPassengerID1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPassengerID1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPurchaseDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPurchaseDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTicketCost, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTicketCost, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPaneTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelScheduleID1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldScheduleID1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsertTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdateTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jTabbedPaneTrainSystem.addTab("Ticket", jPanelTicket);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneTrainSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 934, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneTrainSystem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPaneTrainSystem.getAccessibleContext().setAccessibleName("Order");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteScheduleActionPerformed
       if (!jTextFieldScheduleID.getText().isEmpty()) {
            int scheduleID = Integer.parseInt(jTextFieldScheduleID.getText().trim());
            String startDateTime = jTextFieldStartDateTime.getText().trim();
            String endDateTime = jTextFieldEndDateTime.getText().trim();
            String startLocation = jTextFieldStartLocation.getText().trim();
            String destination = jTextFieldDestination.getText().trim();
            int trainID = Integer.parseInt(jTextFieldTrainID1.getText().trim());

            Schedule schedule = getSchedule(scheduleID);
            if(schedule.getScheduleID() != -1) {
                int option = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to Delete?", "Delete confirmation", JOptionPane.YES_NO_OPTION);
                if(option == 0) {
                    deleteSchedule(scheduleID, startDateTime, endDateTime, startLocation, destination, trainID);
                    refreshSchedulesTable();
                    clearScheduleTextFields();
                }
            }
            else
            {
                alert("Schedule does not exist", "Delete error");
            }
        }
        else
        {
            alert("ID cannot be empty", "Delete error");
        }
    }//GEN-LAST:event_jButtonDeleteScheduleActionPerformed

    private void jButtonUpdateScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateScheduleActionPerformed
         if (!jTextFieldScheduleID.getText().isEmpty()) {
            int scheduleID = Integer.parseInt(jTextFieldScheduleID.getText().trim());
            String startDateTime = jTextFieldStartDateTime.getText().trim();
            String endDateTime = jTextFieldEndDateTime.getText().trim();
            String startLocation = jTextFieldStartLocation.getText().trim();
            String destination = jTextFieldDestination.getText().trim();
            int trainID = Integer.parseInt(jTextFieldTrainID1.getText().trim());

            Schedule schedule = getSchedule(scheduleID);
            if(schedule.getScheduleID()!= -1) {
                updateSchedule(scheduleID, startDateTime, endDateTime, startLocation, destination, trainID);
                refreshSchedulesTable();
            }
            else
            {
                alert("Check in location does not exist", "Update error");
            }
        }
        else
        {
            alert("ID cannot be empty", "Update error");
        }
    }//GEN-LAST:event_jButtonUpdateScheduleActionPerformed

    private void jButtonInsertScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertScheduleActionPerformed
        // TODO add your handling code here:
        //System.out.println(dateTimePicker.datePicker.getDateStringOrEmptyString() + " " + dateTimePicker.timePicker.getTimeStringOrEmptyString()+":00.0");
       if (!jTextFieldScheduleID.getText().isEmpty()) {
            int scheduleID = Integer.parseInt(jTextFieldScheduleID.getText().trim());
            String startDateTime = jTextFieldStartDateTime.getText().trim();
            String endDateTime = jTextFieldEndDateTime.getText().trim();
            String startLocation = jTextFieldStartLocation.getText().trim();
            String destination = jTextFieldDestination.getText().trim();
            
            int trainID = Integer.parseInt(jTextFieldTrainID1.getText().trim());

            addSchedule(scheduleID, startDateTime, endDateTime, startLocation, destination, trainID);
            refreshSchedulesTable();
            clearScheduleTextFields();
        }
        else
        {
            alert("ID cannot be empty", "Insert error");
        }
    }//GEN-LAST:event_jButtonInsertScheduleActionPerformed

    private void jTableScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableScheduleMouseClicked
         int i = jTableSchedule.getSelectedRow();
        TableModel model = jTableSchedule.getModel();
        jTextFieldScheduleID.setText(model.getValueAt(i, 0).toString());
        
        jTextFieldStartDateTime.setText(model.getValueAt(i, 1).toString());
        jTextFieldEndDateTime.setText(model.getValueAt(i, 2).toString());
        jTextFieldStartLocation.setText(model.getValueAt(i, 3).toString());
        jTextFieldDestination.setText(model.getValueAt(i, 4).toString());
        jTextFieldTrainID1.setText(model.getValueAt(i, 5).toString());
    }//GEN-LAST:event_jTableScheduleMouseClicked

    //handles delete button action
    private void jButtonDeletePassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletePassengerActionPerformed
       // TODO add your handling code here:
        if (!jTextFieldPassengerID.getText().isEmpty()) {
            int passengerID = Integer.parseInt(jTextFieldPassengerID.getText().trim());
            String fName = jTextFieldPassengerLastName.getText().trim();
            String lName = jTextFieldPassengerFirstName.getText().trim();
            String email = jTextFieldPassengerEmail.getText().trim();
            Passenger passenger = getPassenger(passengerID);
            if(passenger.getPassengerID() != -1) {
                int option = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to Delete?", "Delete confirmation", JOptionPane.YES_NO_OPTION);
                if(option == 0) {
                    deletePassenger(passengerID, fName, lName, email);
                    refreshPassengersTable();
                    clearPassengerTextFields();
                }
            }
            else
            {
                alert("Customer does not exist", "Delete error");
            }
        }
        else
        {
            alert("Passenger ID cannot be empty", "Delete error");
        }
    }//GEN-LAST:event_jButtonDeletePassengerActionPerformed

    //handles update button action
    private void jButtonUpdatePassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdatePassengerActionPerformed
        // TODO add your handling code here:

        if (!jTextFieldPassengerID.getText().isEmpty()) {
            int passengerID = Integer.parseInt(jTextFieldPassengerID.getText().trim());
            String fName = jTextFieldPassengerFirstName.getText().trim();
            String lName = jTextFieldPassengerLastName.getText().trim();
            String email = jTextFieldPassengerEmail.getText().trim();
            updatePassenger(passengerID, fName, lName, email);
            refreshPassengersTable();
            clearPassengerTextFields();
        }
        
        else
        {
            alert("Passenger ID cannot be empty", "Insert error");
        }
    }//GEN-LAST:event_jButtonUpdatePassengerActionPerformed

    //handle insert button action
    private void jButtonInsertPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertPassengerActionPerformed
        // TODO add your handling code here:

        if (!jTextFieldPassengerID.getText().isEmpty()) {
            int passengerID = Integer.parseInt(jTextFieldPassengerID.getText().trim());
            String fName = jTextFieldPassengerFirstName.getText().trim();
            String lName = jTextFieldPassengerLastName.getText().trim();
            String email = jTextFieldPassengerEmail.getText().trim();
            addPassenger(passengerID, fName, lName, email);
            refreshPassengersTable();
            clearPassengerTextFields();
        }
        else
        {
            alert("Passenger ID cannot be empty", "Insert error");
        }
    }//GEN-LAST:event_jButtonInsertPassengerActionPerformed

    private void jTextFieldPassengerEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPassengerEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPassengerEmailActionPerformed

    //set the values of a row to the textfields
    private void jTablePassengerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePassengerMouseClicked
    // TODO add your handling code here:
        int i = jTablePassenger.getSelectedRow();
        TableModel model = jTablePassenger.getModel();
        jTextFieldPassengerID.setText(model.getValueAt(i, 0).toString());
        jTextFieldPassengerFirstName.setText(model.getValueAt(i, 1).toString());
        jTextFieldPassengerLastName.setText(model.getValueAt(i, 2).toString());
        jTextFieldPassengerEmail.setText(model.getValueAt(i, 3).toString());
    }//GEN-LAST:event_jTablePassengerMouseClicked

    private void jTableTrainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTrainMouseClicked
    // TODO add your handling code here:
        int i = jTableTrain.getSelectedRow();
        TableModel model = jTableTrain.getModel();
        jTextFieldTrainID.setText(model.getValueAt(i, 0).toString());
        jTextFieldTrainType.setText(model.getValueAt(i, 1).toString());
        jTextFieldTrainName.setText(model.getValueAt(i, 2).toString());
        jTextFieldMaxSpeed.setText(model.getValueAt(i, 3).toString());
    }//GEN-LAST:event_jTableTrainMouseClicked

    private void jButtonInsertTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertTrainActionPerformed
 // TODO add your handling code here:

        if (!jTextFieldTrainID.getText().isEmpty()) {
            int trainID = Integer.parseInt(jTextFieldTrainID.getText().trim());
            String tType = jTextFieldTrainType.getText().trim();
            String tName = jTextFieldTrainName.getText().trim();
            int maxSpeed = Integer.parseInt(jTextFieldMaxSpeed.getText().trim());
            addTrain(trainID, tType, tName, maxSpeed);
            refreshTrainsTable();
            clearTrainTextFields();
        }
        else
        {
            alert("Passenger ID cannot be empty", "Insert error");
        }    }//GEN-LAST:event_jButtonInsertTrainActionPerformed

    private void jButtonUpdateTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateTrainActionPerformed
       // TODO add your handling code here:
        if (!jTextFieldTrainID.getText().isEmpty()) {
            int trainID = Integer.parseInt(jTextFieldTrainID.getText().trim());
            String tType = jTextFieldTrainType.getText().trim();
            String tName = jTextFieldTrainName.getText().trim();
            int maxSpeed = Integer.parseInt(jTextFieldMaxSpeed.getText().trim());
            Train train = getTrain(trainID);
            if(train.getTrainID()!= -1) {                
                updateTrain(trainID, tType, tName, maxSpeed);
                refreshTrainsTable();
            }
            else
            {
                alert("Passenger does not exist", "Update error");
            }
        }
        else
        {
            alert("Passenger ID cannot be empty", "Update error");
        }
    }//GEN-LAST:event_jButtonUpdateTrainActionPerformed

    private void jButtonDeleteTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteTrainActionPerformed
       // TODO add your handling code here:
        if (!jTextFieldTrainID.getText().isEmpty()) {
            int trainID = Integer.parseInt(jTextFieldTrainID.getText().trim());
           String tType = jTextFieldTrainType.getText().trim();
            String tName = jTextFieldTrainName.getText().trim();
            int maxSpeed = Integer.parseInt(jTextFieldMaxSpeed.getText().trim());
            Train train = getTrain(trainID);
            if(train.getTrainID()!= -1) {
                int option = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to Delete?", "Delete confirmation", JOptionPane.YES_NO_OPTION);
                if(option == 0) {
                    deleteTrain(trainID, tType, tName, maxSpeed);
                    refreshTrainsTable();
                    clearTrainTextFields();
                }
            }
            else
            {
                alert("Customer does not exist", "Delete error");
            }
        }
        else
        {
            alert("Passenger ID cannot be empty", "Delete error");
        }
    }//GEN-LAST:event_jButtonDeleteTrainActionPerformed

    private void jButtonUpdateTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateTicketActionPerformed
 // TODO add your handling code here:
        if (!jTextFieldTicketID.getText().isEmpty()) {
            int ticketID = Integer.parseInt(jTextFieldTicketID.getText().trim());
            String pDateTime = jTextFieldPurchaseDateTime.getText().trim();
            int tCost = Integer.parseInt(jTextFieldTicketCost.getText().trim());
            int passengerID = Integer.parseInt(jTextFieldPassengerID1.getText().trim());
            int scheduleID = Integer.parseInt(jTextFieldScheduleID1.getText().trim());

            Ticket ticket = getTicket(passengerID);
            if(ticket.getPassengerID() != -1) {                
                updateTicket(ticketID, pDateTime, tCost, passengerID, scheduleID);
                foreignKeyViolationTicket(passengerID);
                refreshTicketsTable();
            }
            else
            {
                alert("Ticket does not exist", "Update error");
            }
        }
        else
        {
            alert("Ticket ID cannot be empty", "Update error");
        }    }//GEN-LAST:event_jButtonUpdateTicketActionPerformed

    private void jButtonDeleteTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteTicketActionPerformed
     // TODO add your handling code here:
        if (!jTextFieldTicketID.getText().isEmpty()) {
            int ticketID = Integer.parseInt(jTextFieldTicketID.getText().trim());
            String pDateTime = jTextFieldPurchaseDateTime.getText().trim();
            int tCost = Integer.parseInt(jTextFieldTicketCost.getText().trim());
            int passengerID = Integer.parseInt(jTextFieldPassengerID1.getText().trim());
            int scheduleID = Integer.parseInt(jTextFieldScheduleID1.getText().trim());

            Ticket ticket = getTicket(passengerID);
            if(ticket.getPassengerID() != -1) {        
                int option = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to Delete?", "Delete confirmation", JOptionPane.YES_NO_OPTION);
                if(option == 0) {
                    deleteTicket(ticketID, pDateTime, tCost, passengerID, scheduleID);
                    foreignKeyViolationTicket(passengerID);
                    refreshTicketsTable();
                    clearTicketTextFields();
                }
            }
            else
            {
                alert("Ticket does not exist", "Delete error");
            }
        }
        else
        {
            alert("Ticket ID cannot be empty", "Delete error");
        }    }//GEN-LAST:event_jButtonDeleteTicketActionPerformed

    private void jButtonInsertTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertTicketActionPerformed
      // TODO add your handling code here:
        //System.out.println(dateTimePicker.datePicker.getDateStringOrEmptyString() + " " + dateTimePicker.timePicker.getTimeStringOrEmptyString()+":00.0");
       if (!jTextFieldTicketID.getText().isEmpty()) {
            int ticketID = Integer.parseInt(jTextFieldTicketID.getText().trim());
            String pDateTime = jTextFieldPurchaseDateTime.getText().trim();
            int tCost = Integer.parseInt(jTextFieldTicketCost.getText().trim());
            int passengerID = Integer.parseInt(jTextFieldPassengerID1.getText().trim());
            int scheduleID = Integer.parseInt(jTextFieldScheduleID1.getText().trim());

            primaryKeyViolationTicket(ticketID);
            addTicket(ticketID, pDateTime, tCost, passengerID, scheduleID);
            refreshTicketsTable();
            clearTicketTextFields();
        }
        else
        {
            alert("ID cannot be empty", "Insert error");
        }    }//GEN-LAST:event_jButtonInsertTicketActionPerformed

    private void jTableTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTicketMouseClicked
      // TODO add your handling code here:
        int i = jTableTicket.getSelectedRow();
        TableModel model = jTableTicket.getModel();
        jTextFieldTicketID.setText(model.getValueAt(i, 0).toString());
        jTextFieldPassengerID.setText(model.getValueAt(i, 1).toString());
        jTextFieldPurchaseDateTime.setText(model.getValueAt(i, 2).toString());
        jTextFieldTicketCost.setText(model.getValueAt(i, 3).toString());
    }//GEN-LAST:event_jTableTicketMouseClicked

    private void jTextFieldDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDestinationActionPerformed



    //method to show an info alert
    public void alert(String msg) {
        JOptionPane.showMessageDialog(rootPane, msg);
    }
    
    //method to check for order's customer id foreign key violation
    public void foreignKeyViolationTicket(int passengerID) {
        if(getTicket(passengerID).getPassengerID() == -1) {
            alert("Passenger ID does not exist", "Foreign Key Violation");
        }
    }
    
    //method to check for customer primary key violation
    public void primaryKeyViolationPassenger(int passengerID) {
        if(getPassenger(passengerID).getPassengerID() != -1) {
            alert("Another passenger already exists with same Passenger ID, please try another Passenger ID", "Primary Key Violation");
        }
    }
    
    //method to check for order primary key violation
    public void primaryKeyViolationTrain(int trainID) {
        if(getTrain(trainID).getTrainID() != -1) {
            alert("Another train already exists with same Train ID, please try another Train ID", "Primary Key Violation");
        }
    }
    
    public void primaryKeyViolationSchedule(int scheduleID) {
        if(getSchedule(scheduleID).getScheduleID() != -1) {
            alert("Another schedule already exists with same schedule ID, please try another schedule ID", "Primary Key Violation");
        }
    }
    
     public void primaryKeyViolationTicket(int ticketID) {
        if(getTicket(ticketID).getTicketID() != -1) {
            alert("Another ticket already exists with same ticket ID, please try another ticket ID", "Primary Key Violation");
        }
    }
    
    //method to show an error alert
    public void alert(String msg, String title) {
        JOptionPane.showMessageDialog(rootPane, msg, title, JOptionPane.ERROR_MESSAGE);
    }

    /**
     * PASSENGER CRUD FUNCTIONS
    */
    private static void addPassenger(int passengerID,String fName,String lName,String email) {
        Passenger passenger;
        passenger = new Passenger(passengerID, fName, lName, email);
        passengerDAO.insert(passenger);
    }
    
    private static void updatePassenger(int passengerID,String fName,String lName,String email) {
        Passenger passenger;
        passenger = new Passenger(passengerID, fName, lName, email);
        passengerDAO.update(passenger);
    }
    
    private static void deletePassenger(int passengerID,String fName,String lName,String email) {
        Passenger contact;
        contact = new Passenger(passengerID, fName, lName, email);
        passengerDAO.delete(contact);
    }
    
    static Passenger getPassenger(int id) {
        Optional<Passenger> passenger = passengerDAO.get(id);
        return passenger.orElseGet(() -> new Passenger(-1, "Non-exist", "Non-exist", "Non-exist"));
    }
    
    
    /**
     * SCHEDULE CRUD FUNCTIONS
    */
    private static void addSchedule(int scheduleID,String startDateTime,String endDateTime,String startLocation,String destination, int trainID) {
        Schedule schedule;
        schedule = new Schedule(scheduleID, startDateTime, endDateTime, startLocation, destination, trainID);
        scheduleDAO.insert(schedule);
    }
    
    private static void updateSchedule(int scheduleID,String startDateTime,String endDateTime,String startLocation,String destination, int trainID) {
        Schedule schedule;
        schedule = new Schedule(scheduleID, startDateTime, endDateTime, startLocation, destination, trainID);
        scheduleDAO.update(schedule);
    }
    
    private static void deleteSchedule(int scheduleID,String startDateTime,String endDateTime,String startLocation,String destination, int trainID) {
        Schedule schedule;
        schedule = new Schedule(scheduleID, startDateTime, endDateTime, startLocation, destination, trainID);
        scheduleDAO.delete(schedule);
    }
    static Schedule getSchedule(int scheduleID) {
        Optional<Schedule> schedule = scheduleDAO.get(scheduleID);
        return schedule.orElseGet(() -> new Schedule(-1, "Non-exist", "Non-exist", "Non-exist", "Non-exist", -1));
    }
    
     /**
     * TRAIN CRUD FUNCTIONS
    */
    private static void addTrain(int trainID,String tType,String tName,int maxSpeed) {
        Train train;
        train = new Train(trainID, tType, tName, maxSpeed);
        trainDAO.insert(train);
    }
    
    private static void updateTrain(int trainID,String tType,String tName,int maxSpeed) {
        Train train;
        train = new Train(trainID, tType, tName, maxSpeed);
        trainDAO.update(train);
    }
    
    private static void deleteTrain(int trainID,String tType,String tName,int maxSpeed) {
        Train train;
        train = new Train(trainID, tType, tName, maxSpeed);
        trainDAO.delete(train);
    }
     static Train getTrain(int trainID) {
        Optional<Train> train = trainDAO.get(trainID);
        return train.orElseGet(() -> new Train(-1, "Non-exist", "Non-exist", -1));
    }
    
    /**
     * TRAIN CRUD FUNCTIONS
    */
    private static void addTicket(int ticketID,String pDateTime,int tCost,int passengerID, int scheduleID) {
        Ticket ticket;
        ticket = new Ticket(ticketID, tCost, pDateTime, passengerID, scheduleID);
        ticketDAO.insert(ticket);
    }
    
    private static void updateTicket(int ticketID,String pDateTime,int tCost,int passengerID, int scheduleID) {
        Ticket ticket;
        ticket = new Ticket(ticketID, tCost, pDateTime, passengerID, scheduleID);
        ticketDAO.update(ticket);
    }
    
    private static void deleteTicket(int ticketID,String pDateTime,int tCost,int passengerID, int scheduleID) {
        Ticket ticket;
        ticket = new Ticket(ticketID, tCost, pDateTime, passengerID, scheduleID);
        ticketDAO.delete(ticket);
    }
    static Ticket getTicket(int passengerID) {
        Optional<Ticket> ticket = ticketDAO.get(passengerID);
        return ticket.orElseGet(() -> new Ticket(-1, -1, "Non-exist", -1, -1));
    }
    
    //method to clear the customer txt fields
    private void clearPassengerTextFields() {
        jTextFieldPassengerID.setText("");
        jTextFieldPassengerFirstName.setText("");
        jTextFieldPassengerLastName.setText("");
        jTextFieldPassengerEmail.setText("");
    }
    
    //method to clear the order txt fields
    private void clearScheduleTextFields() {
        jTextFieldScheduleID.setText("");
        jTextFieldStartDateTime.setText("");
        jTextFieldEndDateTime.setText("");
        jTextFieldStartLocation.setText("");
        jTextFieldDestination.setText("");
    }
    private void clearTrainTextFields() {
        jTextFieldTrainID.setText("");
        jTextFieldTrainType.setText("");
        jTextFieldTrainName.setText("");
        jTextFieldMaxSpeed.setText("");
    }
    private void clearTicketTextFields() {
        jTextFieldTicketID.setText("");
        jTextFieldPassengerID.setText("");
        jTextFieldPurchaseDateTime.setText("");
        jTextFieldTicketCost.setText("");
    }

    //fetch customer table
    private void refreshPassengersTable() {
        List<Passenger> passengers = passengerDAO.getAll();
        DefaultTableModel model = (DefaultTableModel) jTablePassenger.getModel();
        //Clear all items in tblContacts
        for(int i = model.getRowCount() - 1; i >= 0; i-- ) {
            model.removeRow(i);
        }
        for (Passenger passenger : passengers) {
                Object[] row = new Object[4];
                row[0] = passenger.getPassengerID();
                row[1] = passenger.getPassengerFirstName();
                row[2] = passenger.getPassengerLastName();
                row[3] = passenger.getPassengerEmail();
                model.addRow(row);
        }
    }
    
    //fetch order table
    private void refreshSchedulesTable() {
        List<Schedule> schedules = scheduleDAO.getAll();
        DefaultTableModel model = (DefaultTableModel) jTableSchedule.getModel();
        //Clear all items in tblContacts
        for(int i = model.getRowCount() - 1; i >= 0; i-- ) {
            model.removeRow(i);
        }
        for (Schedule schedule : schedules) {
                Object[] row = new Object[6];
                row[0] = schedule.getScheduleID();
                row[1] = schedule.getStartDateTime();
                row[2] = schedule.getEndDateTime();
                row[3] = schedule.getStartLocation();
                row[4] = schedule.getDestination();
                row[5] = schedule.getTrainID();

                model.addRow(row);
        }
    }
    private void refreshTrainsTable() {
        List<Train> trains = trainDAO.getAll();
        DefaultTableModel model = (DefaultTableModel) jTableTrain.getModel();
        //Clear all items in tblContacts
        for(int i = model.getRowCount() - 1; i >= 0; i-- ) {
            model.removeRow(i);
        }
        for (Train train : trains) {
                Object[] row = new Object[4];
                row[0] = train.getTrainID();
                row[1] = train.getTrainType();
                row[2] = train.getTrainName();
                row[3] = train.getMaxSpeed();
                model.addRow(row);
        }
    }
    private void refreshTicketsTable() {
        List<Ticket> tickets = ticketDAO.getAll();
        DefaultTableModel model = (DefaultTableModel) jTableTicket.getModel();
        //Clear all items in tblContacts
        for(int i = model.getRowCount() - 1; i >= 0; i-- ) {
            model.removeRow(i);
        }
        for (Ticket ticket : tickets) {
                Object[] row = new Object[5];
                row[0] = ticket.getTicketID();
                row[1] = ticket.getPassengerID();
                row[2] = ticket.getPurchaseDateTime();
                row[3] = ticket.getTicketCost();
                row[4] = ticket.getScheduleID();

                model.addRow(row);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        passengerDAO = new PassengerDAO();
        scheduleDAO = new ScheduleDAO();
        trainDAO = new TrainDAO();
        ticketDAO = new TicketDAO();

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeletePassenger;
    private javax.swing.JButton jButtonDeleteSchedule;
    private javax.swing.JButton jButtonDeleteTicket;
    private javax.swing.JButton jButtonDeleteTrain;
    private javax.swing.JButton jButtonInsertPassenger;
    private javax.swing.JButton jButtonInsertSchedule;
    private javax.swing.JButton jButtonInsertTicket;
    private javax.swing.JButton jButtonInsertTrain;
    private javax.swing.JButton jButtonUpdatePassenger;
    private javax.swing.JButton jButtonUpdateSchedule;
    private javax.swing.JButton jButtonUpdateTicket;
    private javax.swing.JButton jButtonUpdateTrain;
    private javax.swing.JLabel jLabelDestination;
    private javax.swing.JLabel jLabelEndDateTime;
    private javax.swing.JLabel jLabelItemName2;
    private javax.swing.JLabel jLabelMaxSpeed;
    private javax.swing.JLabel jLabelPassengerEmail;
    private javax.swing.JLabel jLabelPassengerFirstName;
    private javax.swing.JLabel jLabelPassengerID;
    private javax.swing.JLabel jLabelPassengerID1;
    private javax.swing.JLabel jLabelPassengerLastName;
    private javax.swing.JLabel jLabelPurchaseDateTime;
    private javax.swing.JLabel jLabelScheduleID;
    private javax.swing.JLabel jLabelScheduleID1;
    private javax.swing.JLabel jLabelStartDateTime;
    private javax.swing.JLabel jLabelStartLocation;
    private javax.swing.JLabel jLabelTicketCost;
    private javax.swing.JLabel jLabelTicketID;
    private javax.swing.JLabel jLabelTrainID;
    private javax.swing.JLabel jLabelTrainID1;
    private javax.swing.JLabel jLabelTrainName;
    private javax.swing.JLabel jLabelTrainType;
    private javax.swing.JPanel jPanelPassenger;
    private javax.swing.JPanel jPanelSchedule;
    private javax.swing.JPanel jPanelTicket;
    private javax.swing.JPanel jPanelTrain;
    private javax.swing.JScrollPane jScrollPaneOrder;
    private javax.swing.JScrollPane jScrollPanePassenger;
    private javax.swing.JScrollPane jScrollPaneTicket;
    private javax.swing.JScrollPane jScrollPaneTrain;
    private javax.swing.JTabbedPane jTabbedPaneTrainSystem;
    private javax.swing.JTable jTablePassenger;
    private javax.swing.JTable jTableSchedule;
    private javax.swing.JTable jTableTicket;
    private javax.swing.JTable jTableTrain;
    private javax.swing.JTextField jTextFieldDestination;
    private javax.swing.JTextField jTextFieldEndDateTime;
    private javax.swing.JTextField jTextFieldMaxSpeed;
    private javax.swing.JTextField jTextFieldPassengerEmail;
    private javax.swing.JTextField jTextFieldPassengerFirstName;
    private javax.swing.JTextField jTextFieldPassengerID;
    private javax.swing.JTextField jTextFieldPassengerID1;
    private javax.swing.JTextField jTextFieldPassengerLastName;
    private javax.swing.JTextField jTextFieldPurchaseDateTime;
    private javax.swing.JTextField jTextFieldScheduleID;
    private javax.swing.JTextField jTextFieldScheduleID1;
    private javax.swing.JTextField jTextFieldStartDateTime;
    private javax.swing.JTextField jTextFieldStartLocation;
    private javax.swing.JTextField jTextFieldTicketCost;
    private javax.swing.JTextField jTextFieldTicketID;
    private javax.swing.JTextField jTextFieldTrainID;
    private javax.swing.JTextField jTextFieldTrainID1;
    private javax.swing.JTextField jTextFieldTrainName;
    private javax.swing.JTextField jTextFieldTrainType;
    // End of variables declaration//GEN-END:variables
}
